CREATE TABLE contact_enquiries (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  reference VARCHAR(20) NOT NULL,
  full_name VARCHAR(120) NOT NULL,
  email VARCHAR(255) NOT NULL,
  country_code VARCHAR(8) NOT NULL,
  mobile_number VARCHAR(20) NOT NULL,
  business_name VARCHAR(160) NULL,
  website VARCHAR(255) NULL,
  topic VARCHAR(60) NOT NULL,
  source VARCHAR(60) NULL,
  source_other VARCHAR(160) NULL,
  message TEXT NOT NULL,
  consent_id BIGINT UNSIGNED NULL,
  source_page VARCHAR(255) NULL,
  utm_source VARCHAR(150) NULL,
  utm_medium VARCHAR(150) NULL,
  utm_campaign VARCHAR(150) NULL,
  utm_term VARCHAR(150) NULL,
  utm_content VARCHAR(150) NULL,
  status ENUM('new','read','replied','spam','archived') NOT NULL DEFAULT 'new',
  ip_hash CHAR(64) NULL,
  user_agent VARCHAR(255) NULL,
  is_test TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_contact_reference (reference),
  KEY idx_contact_status_created (status, created_at),
  KEY idx_contact_email (email),
  CONSTRAINT fk_contact_consent FOREIGN KEY (consent_id) REFERENCES consents (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
