CREATE TABLE preview_applications (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  reference VARCHAR(20) NOT NULL,
  full_name VARCHAR(120) NOT NULL,
  email VARCHAR(255) NOT NULL,
  country_code VARCHAR(8) NOT NULL,
  mobile_number VARCHAR(20) NOT NULL,
  business_name VARCHAR(160) NOT NULL,
  website VARCHAR(255) NULL,
  gbp_url VARCHAR(500) NULL,
  country VARCHAR(80) NOT NULL,
  city VARCHAR(120) NOT NULL,
  category VARCHAR(80) NOT NULL,
  primary_service VARCHAR(200) NULL,
  problem TEXT NULL,
  consent_id BIGINT UNSIGNED NULL,
  source_page VARCHAR(255) NULL,
  utm_source VARCHAR(150) NULL,
  utm_medium VARCHAR(150) NULL,
  utm_campaign VARCHAR(150) NULL,
  utm_term VARCHAR(150) NULL,
  utm_content VARCHAR(150) NULL,
  status ENUM('new','reviewing','qualified','declined','preview_sent','activated','expired') NOT NULL DEFAULT 'new',
  ip_hash CHAR(64) NULL,
  user_agent VARCHAR(255) NULL,
  is_test TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_preview_reference (reference),
  KEY idx_preview_status_created (status, created_at),
  KEY idx_preview_email (email),
  CONSTRAINT fk_preview_consent FOREIGN KEY (consent_id) REFERENCES consents (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
