CREATE TABLE bookings (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  reference VARCHAR(20) NOT NULL,
  idempotency_key CHAR(36) NOT NULL,
  slot_start_utc DATETIME NOT NULL,
  slot_end_utc DATETIME NOT NULL,
  slot_lock TINYINT(1) NULL DEFAULT 1 COMMENT '1 while the slot is held; NULL once cancelled so it can be rebooked',
  visitor_timezone VARCHAR(64) NOT NULL,
  sfd_timezone VARCHAR(64) NOT NULL,
  full_name VARCHAR(120) NOT NULL,
  email VARCHAR(255) NOT NULL,
  country_code VARCHAR(8) NOT NULL,
  mobile_number VARCHAR(20) NOT NULL,
  business_name VARCHAR(160) NULL,
  website VARCHAR(255) NULL,
  country VARCHAR(80) NULL,
  message TEXT NOT NULL,
  consent_id BIGINT UNSIGNED NULL,
  source_page VARCHAR(255) NULL,
  utm_source VARCHAR(150) NULL,
  utm_medium VARCHAR(150) NULL,
  utm_campaign VARCHAR(150) NULL,
  utm_term VARCHAR(150) NULL,
  utm_content VARCHAR(150) NULL,
  status ENUM('pending_calendar','confirmed','cancelled','completed','no_show','failed') NOT NULL DEFAULT 'pending_calendar',
  google_event_id VARCHAR(255) NULL,
  meet_url VARCHAR(255) NULL,
  calendar_synced_at DATETIME NULL,
  ip_hash CHAR(64) NULL,
  user_agent VARCHAR(255) NULL,
  is_test TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_booking_reference (reference),
  UNIQUE KEY uq_booking_idempotency (idempotency_key),
  UNIQUE KEY uq_booking_slot (slot_start_utc, slot_lock),
  KEY idx_booking_status_start (status, slot_start_utc),
  KEY idx_booking_email (email),
  CONSTRAINT fk_booking_consent FOREIGN KEY (consent_id) REFERENCES consents (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
