import home from '@/data/home.json';
import { ArrowDown, ArrowUpRight, Monitor, MapPin, Workflow, MessagesSquare, Video, Megaphone } from 'lucide-react';
import HeroScene from '@/components/hero-scene';
import PageMotion from '@/components/page-motion';
import Booking from '@/components/booking';
import booking from '@/data/pages/book-a-call.json';
import FAQ from '@/components/faq';
const icons = [Monitor, MapPin, Workflow, Video, Megaphone, MessagesSquare];
export default function Home() {return <main id="main"><PageMotion/><section className="hero-sequence" aria-labelledby="hero-title"><div className="hero-stage"><HeroScene/><div className="hero-copy"><p className="eyebrow">{home.hero.eyebrow}</p><h1 id="hero-title">{home.hero.title}<br/><span>{home.hero.accent}</span></h1><p className="hero-description">{home.hero.description}</p><a className="primary-button" href="/book-a-call">{home.hero.cta}<ArrowUpRight size={17}/></a></div><a className="scroll-cue" href="#services">{home.hero.scroll}<ArrowDown size={17}/></a><div className="scene-intro" aria-hidden="true"><span>{home.services.eyebrow}</span><p>{home.services.title}</p></div><div className="hero-footnote">{home.hero.footnote}</div></div></section>
<section id="services" className="section container"><div className="section-heading reveal"><p className="eyebrow">{home.services.eyebrow}</p><h2>{home.services.title}</h2><p>{home.services.description}</p></div><div className="service-grid" data-card-spread>{home.services.items.map((s,i)=>{const Icon=icons[i];return <a className="service-card" href={`/services/${s.slug}`} key={s.slug}><div className="service-top"><Icon size={25} strokeWidth={1.3}/><span>0{i+1}</span></div><h3>{s.title}</h3><p>{s.description}</p><span className="text-link">{home.services.link}<ArrowUpRight size={16}/></span></a>})}</div></section>
<section className="statement-section container"><p className="eyebrow reveal">{home.statement.eyebrow}</p><h2 className="moving-heading"><span>{home.statement.line1}</span><span>{home.statement.line2}</span></h2><div className="statement-copy reveal"><p>{home.statement.description}</p><a className="text-link" href="/about">{home.statement.link}<ArrowUpRight size={17}/></a></div></section>
<section className="section container"><div className="section-heading reveal"><p className="eyebrow">{home.process.eyebrow}</p><h2>{home.process.title}</h2></div><div className="process-grid" data-card-spread>{home.process.items.map((item,i)=><article key={item.title}><span className="process-number">0{i+1}</span><h3>{item.title}</h3><p>{item.description}</p></article>)}</div></section>
<section className="section container pricing-teaser"><div className="reveal"><p className="eyebrow">{home.pricing.eyebrow}</p><h2>{home.pricing.title}</h2><p>{home.pricing.description}</p><a className="primary-button" href="/pricing">{home.pricing.link}<ArrowUpRight size={17}/></a></div><div className="scope-list reveal">{home.pricing.items.map(item=><div key={item.title}><h3>{item.title}</h3><p>{item.description}</p><span>{home.pricing.priceLabel}</span></div>)}</div></section>
<section className="section container"><div className="section-heading reveal"><p className="eyebrow">{home.tools.eyebrow}</p><h2>{home.tools.title}</h2><p>{home.tools.description}</p></div><div className="tools-grid">{home.tools.items.map((tool,i)=><a className="tool-card reveal" href={`/free-tools/${tool.slug}`} key={tool.slug}><span className="tool-symbol" aria-hidden="true">{['Aa','↔','≡'][i]}</span><h3>{tool.title}</h3><p>{tool.description}</p><span className="text-link">{home.tools.link}<ArrowUpRight size={16}/></span></a>)}</div></section>
<section id="booking" className="closing-section container"><p className="eyebrow">{home.closing.eyebrow}</p><h2>{home.closing.title}</h2><p>{home.closing.description}</p><div className="home-booking"><Booking data={booking.booking}/></div></section><section className="container section narrow"><h2>{home.faq.title}</h2><FAQ items={home.faq.items}/></section></main>}

