import home from '@/data/home.json';
import { ArrowDown, ArrowUpRight, Monitor, MapPin, Workflow, MessagesSquare, Video, Megaphone } from 'lucide-react';
import HeroScene from '@/components/hero-scene';
import HeroSystem from '@/components/hero-system';
import PageMotion from '@/components/page-motion';
import Booking from '@/components/booking';
import booking from '@/data/pages/book-a-call.json';
import FAQ from '@/components/faq';
import { ServiceVisual, ToolVisual } from '@/components/home-visuals';
import ScrollLink from '@/components/scroll-link';
const icons = [Monitor, MapPin, Workflow, Video, Megaphone, MessagesSquare];
export default function Home() {return <main id="main"><PageMotion/><section className="hero-sequence" aria-labelledby="hero-title"><div className="hero-stage"><HeroScene/><HeroSystem/><div className="hero-copy"><p className="eyebrow">{home.hero.eyebrow}</p><h1 id="hero-title">{home.hero.title} <span>{home.hero.accent}</span></h1><p className="hero-description">{home.hero.description}</p><div className="hero-actions"><a className="primary-button" href="/book-a-call">{home.hero.cta}<ArrowUpRight size={17}/></a><a className="secondary-button" href={home.hero.cta2Href}>{home.hero.cta2}<ArrowUpRight size={17}/></a></div></div><ScrollLink targetId="services" className="scroll-cue">{home.hero.scroll}<ArrowDown size={17}/></ScrollLink><div className="scene-intro" aria-hidden="true"><span>{home.services.eyebrow}</span><p>{home.services.title}</p></div><div className="hero-footnote">{home.hero.footnote}</div></div></section>
<section className="trust-strip"><div className="container trust-strip-row">{home.services.items.map(s=><span key={s.slug}>{s.title}</span>)}</div></section>
<section id="services" className="section"><div className="container"><div className="section-heading reveal"><p className="eyebrow">{home.services.eyebrow}</p><h2>{home.services.title}</h2><p>{home.services.description}</p></div><div className="service-grid" data-card-spread>{home.services.items.map((s,i)=>{const Icon=icons[i];return <a className="service-card" href={`/services/${s.slug}`} key={s.slug}><div className="service-top"><Icon size={25} strokeWidth={1.3}/><span>0{i+1}</span></div><ServiceVisual slug={s.slug}/><h3>{s.title}</h3><p>{s.description}</p><span className="text-link">{home.services.link}<ArrowUpRight size={16}/></span></a>})}</div></div></section>
<section className="statement-section on-light bg-light"><div className="container"><p className="eyebrow reveal">{home.statement.eyebrow}</p><h2 className="moving-heading"><span>{home.statement.line1}</span><span>{home.statement.line2}</span></h2><div className="statement-copy reveal"><p>{home.statement.description}</p><a className="text-link" href="/about">{home.statement.link}<ArrowUpRight size={17}/></a></div></div></section>
<section className="section process-section"><div className="container"><div className="section-heading reveal"><p className="eyebrow">{home.process.eyebrow}</p><h2>{home.process.title}</h2></div><div className="process-grid">{home.process.items.map((item,i)=><article className="reveal" key={item.title}><span className="process-node" style={{animationDelay:`${i*.6}s`}}><span className="process-number">0{i+1}</span></span><h3>{item.title}</h3><p>{item.description}</p></article>)}</div></div></section>
<section className="section on-light bg-light-alt"><div className="container pricing-teaser"><div className="reveal"><p className="eyebrow">{home.pricing.eyebrow}</p><h2>{home.pricing.title}</h2><p>{home.pricing.description}</p><a className="primary-button" href="/pricing">{home.pricing.link}<ArrowUpRight size={17}/></a></div><div className="scope-list reveal">{home.pricing.items.map((item,i)=><div key={item.title} data-index={`0${i+1}`}><h3>{item.title}</h3><p>{item.description}</p><span>{home.pricing.priceLabel}</span></div>)}</div></div></section>
<section className="section home-tools-section"><div className="container"><div className="section-heading reveal"><p className="eyebrow">{home.tools.eyebrow}</p><h2>{home.tools.title}</h2><p>{home.tools.description}</p></div><div className="tools-grid" data-card-spread>{home.tools.items.map(tool=><a className="tool-card" href={`/free-tools/${tool.slug}`} key={tool.slug}><ToolVisual slug={tool.slug}/><h3>{tool.title}</h3><p>{tool.description}</p><span className="text-link">{home.tools.link}<ArrowUpRight size={16}/></span></a>)}</div></div></section>
<section id="booking" className="closing-section"><div className="container closing-split"><div className="closing-intro reveal"><p className="eyebrow">{home.closing.eyebrow}</p><h2>{home.closing.title}</h2><p>{home.closing.description}</p></div><div className="home-booking reveal"><Booking data={booking.booking}/></div></div></section><section className="section home-faq-section on-light bg-light"><div className="container narrow"><h2>{home.faq.title}</h2><FAQ items={home.faq.items}/></div></section></main>}

