'use client';
import {useState} from 'react';
import {usePathname} from 'next/navigation';
import {Menu,ChevronDown,ArrowUpRight} from 'lucide-react';
import {Sheet,SheetTrigger,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuItem} from '@/components/ui/dropdown-menu';
import site from '@/data/site.json';
import navigation from '@/data/navigation.json';
export function Brand(){return <a className="brand" href="/" aria-label={site.name}><svg viewBox="0 0 32 36" width="26" height="30" aria-hidden="true"><path d="M7 1h24L19 13H8L1 20V7zM25 35H1l12-12h11l7-7v13z" fill="currentColor"/></svg><span>{site.shortName}</span></a>}
export default function Header(){const [open,setOpen]=useState(false);const path=usePathname();return <header className="site-header"><Brand/><nav className="desktop-nav" aria-label="Main navigation">{navigation.map(item=>item.children?<DropdownMenu key={item.label}><DropdownMenuTrigger className="nav-button">{item.label}<ChevronDown size={12}/></DropdownMenuTrigger><DropdownMenuContent className="nav-dropdown" sideOffset={20}>{item.children.map(child=><DropdownMenuItem key={child.href} render={<a href={child.href}/>}>{child.label}</DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu>:<a key={item.href} className={path===item.href?'active':''} href={item.href}>{item.label}</a>)}</nav><a href="/book-a-call" className="header-cta">{site.bookLabel}<ArrowUpRight size={14}/></a><div className="mobile-nav"><Sheet open={open} onOpenChange={setOpen}><SheetTrigger className="menu-button" aria-label={site.menuLabel}><Menu size={27}/></SheetTrigger><SheetContent className="mobile-sheet"><SheetTitle className="sr-only">{site.menuLabel}</SheetTitle><SheetDescription className="sr-only">Explore SynergyFirst Digital</SheetDescription><Brand/><nav aria-label="Mobile navigation">{navigation.map(item=><div key={item.label}>{item.children?<details><summary>{item.label}<ChevronDown size={16}/></summary><div>{item.children.map(child=><a href={child.href} onClick={()=>setOpen(false)} key={child.href}>{child.label}</a>)}</div></details>:<a href={item.href} onClick={()=>setOpen(false)}>{item.label}</a>}</div>)}<a className="primary-button" href="/book-a-call" onClick={()=>setOpen(false)}>{site.bookLabel}<ArrowUpRight size={16}/></a></nav></SheetContent></Sheet></div></header>}
