'use strict';

// Build-time SEO files: sitemap.xml, robots.txt (both served from dist/) and the
// nginx redirect/404 snippet (written to deploy/, NOT dist/, so it is never
// publicly downloadable). Every absolute URL uses site.productionDomain only.

const fs = require('fs');
const path = require('path');

const NON_INDEXABLE_TYPES = ['internal-diagnostic', 'not-found'];

function isIndexable(page) {
  if (NON_INDEXABLE_TYPES.includes(page.type)) return false;
  return !/noindex/i.test((page.seo && page.seo.robots) || '');
}

function escapeXml(value) {
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function buildSitemap({ site, pages }) {
  const entries = pages
    .map((p) => p.data)
    .filter(isIndexable)
    .sort((a, b) => a.canonicalPath.localeCompare(b.canonicalPath))
    .map((page) => {
      const lastmod = /^\d{4}-\d{2}-\d{2}$/.test(page.lastUpdated || '') ? page.lastUpdated : null;
      return (
        '  <url>\n' +
        `    <loc>${escapeXml(site.productionDomain + page.canonicalPath)}</loc>\n` +
        (lastmod ? `    <lastmod>${lastmod}</lastmod>\n` : '') +
        '  </url>'
      );
    });

  return (
    '<?xml version="1.0" encoding="UTF-8"?>\n' +
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' +
    entries.join('\n') +
    '\n</urlset>\n'
  );
}

// Production robots.txt: everything crawlable (CLAUDE.md rule 8). Preview sites
// are a separate build (docs/06) and must ship their own Disallow-all file.
function buildRobots({ site }) {
  return `User-agent: *\nAllow: /\n\nSitemap: ${site.productionDomain}/sitemap.xml\n`;
}

// Nginx snippet for the CloudPanel vhost (Contabo VPS). Include it inside the
// site's `server { }` block. Directory URLs without a trailing slash are
// redirected by nginx itself (single-hop 301) thanks to `try_files $uri $uri/`.
function buildNginxConfig({ redirects }) {
  const lines = [
    '# Generated by scripts/generate-seo.js. Do not edit; change data/redirects.json and rebuild.',
    '# Paste inside the vhost `server { }` block in CloudPanel (Vhost editor).',
    '',
    '# Relative Location headers so redirects keep the public scheme/host.',
    'absolute_redirect off;',
    '',
    '# Real 404 status with the branded page. Never fall back to the homepage.',
    'error_page 404 /404.html;',
    'location = /404.html { internal; }',
    '',
    '# /some/path/index.html -> /some/path/ (one hop). Uses $request_uri so nginx\'s',
    '# own internal index lookup is not caught by the rule.',
    'if ($request_uri ~ ^(.*)/index\\.html(\\?.*)?$) { return 301 $1/$2; }',
    '',
    '# Never serve dotfiles (.env and friends).',
    'location ~ /\\.(?!well-known) { deny all; }',
    '',
    '# Form and booking API: every /api/ path is handled by dist/api/index.php (PHP-FPM).',
    'location /api/ { try_files $uri /api/index.php?$query_string; }',
    '',
    '# /some/path -> /some/path/ (301) is done by nginx for directories; missing',
    '# paths fall through to error_page 404 above.',
    'location / { try_files $uri $uri/ =404; }',
  ];

  if (redirects.length > 0) {
    lines.push('', '# Permanent redirects for replaced URLs (data/redirects.json).');
    for (const { from, to } of redirects) {
      const bare = from.replace(/\/$/, '');
      lines.push(`location = ${from} { return 301 ${to}; }`);
      if (bare) lines.push(`location = ${bare} { return 301 ${to}; }`);
    }
  }
  return lines.join('\n') + '\n';
}

function writeSeoFiles({ rootDir, outDir, sharedData, pages }) {
  const site = sharedData['site.json'];
  const redirects = sharedData['redirects.json'] || [];
  const deployDir = path.join(rootDir, 'deploy');

  fs.writeFileSync(path.join(outDir, 'sitemap.xml'), buildSitemap({ site, pages }), 'utf8');
  fs.writeFileSync(path.join(outDir, 'robots.txt'), buildRobots({ site }), 'utf8');
  fs.mkdirSync(deployDir, { recursive: true });
  fs.writeFileSync(path.join(deployDir, 'nginx-redirects.conf'), buildNginxConfig({ redirects }), 'utf8');

  return ['dist/sitemap.xml', 'dist/robots.txt', 'deploy/nginx-redirects.conf'];
}

module.exports = { isIndexable, buildSitemap, buildRobots, buildNginxConfig, writeSeoFiles };
