import fs from 'node:fs';
import path from 'node:path';
const walk=dir=>fs.readdirSync(dir,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(dir,e.name)):[path.join(dir,e.name)]);
for(const file of walk('data').filter(f=>f.endsWith('.json'))){const data=JSON.parse(fs.readFileSync(file,'utf8'));const normalize=value=>{if(Array.isArray(value))return value.map(normalize);if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,k==='href'&&typeof v==='string'&&v.startsWith('/')&&v!=='/'?v.replace(/\/$/,''):normalize(v)]));return value};fs.writeFileSync(file,JSON.stringify(normalize(data),null,2)+'\n')}
for(const file of [...walk('app'),...walk('components')].filter(f=>f.endsWith('.tsx')&&!f.includes('components'+path.sep+'ui'))){let text=fs.readFileSync(file,'utf8');text=text.replace(/href="(\/[^"#]+?)\/"/g,'href="$1"').replace(/(\$\{(?:s|tool|p)\.slug\})\//g,'$1').replaceAll("site.url+'/'+p.slug+'/'","site.url+'/'+p.slug");fs.writeFileSync(file,text)}
const route='app/[...slug]/page.tsx';let source=fs.readFileSync(route,'utf8');source=source.replace(/const breadcrumbs=\[.*?\];return/,"const parents=slug.slice(0,-1).map((part,i)=>({name:part.replaceAll('-',' '),slug:slug.slice(0,i+1).join('/')})).filter(p=>getPage(p.slug));const breadcrumbs=[{name:'Home',url:site.url+'/'},...parents.map(p=>({name:p.name,url:site.url+'/'+p.slug})),{name:p.title,url:site.url+'/'+p.slug}];return");fs.writeFileSync(route,source);
const tool='components/tools.tsx';source=fs.readFileSync(tool,'utf8');if(!source.includes("from '@/components/ui/table'")){source=source.replace("type UI=Record<string,string>;","import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';\ntype UI=Record<string,string>;");for(const [a,b] of [['table','Table'],['thead','TableHeader'],['tbody','TableBody'],['tr','TableRow'],['th','TableHead'],['td','TableCell']])source=source.replace(new RegExp('<'+a+'(?=[ >])','g'),'<'+b).replaceAll('</'+a+'>','</'+b+'>');fs.writeFileSync(tool,source)}
const pkg=JSON.parse(fs.readFileSync('package.json','utf8'));pkg.name='synergyfirst-digital';pkg.scripts.build='vinext build && node scripts/finalize-static.mjs';pkg.scripts.check='tsc --noEmit && node scripts/validate-export.mjs';pkg.scripts['test:tools']='node --experimental-strip-types --test scripts/tool-calculations.test.mjs';fs.writeFileSync('package.json',JSON.stringify(pkg,null,2)+'\n');
console.log('Normalized internal routes and build scripts.');
